#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"content-type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n");

            
            #line 8 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (File.Exists(Server.MapPath("~/areas/manager/content/img/icon.ico")))
    {

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 334), Tuple.Create("\"", 377)
, Tuple.Create(Tuple.Create("", 341), Tuple.Create<System.Object, System.Int32>(Href("~/areas/manager/content/img/icon.ico")
, 341), false)
);

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n");

WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 421), Tuple.Create("\"", 464)
, Tuple.Create(Tuple.Create("", 428), Tuple.Create<System.Object, System.Int32>(Href("~/areas/manager/content/img/icon.ico")
, 428), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral("> \r\n");

            
            #line 12 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 542), Tuple.Create("\"", 594)
, Tuple.Create(Tuple.Create("", 549), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/img/icon.ico")
, 549), false)
);

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n");

WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 638), Tuple.Create("\"", 690)
, Tuple.Create(Tuple.Create("", 645), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/img/icon.ico")
, 645), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral("> \r\n");

            
            #line 17 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 751), Tuple.Create("\"", 813)
, Tuple.Create(Tuple.Create("", 758), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/css/ext/chosen.min.css")
, 758), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("/>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 860), Tuple.Create("\"", 938)
, Tuple.Create(Tuple.Create("", 867), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/css/ext/jquery-ui-1.9.2.custom.min.css")
, 867), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 986), Tuple.Create("\"", 1043)
, Tuple.Create(Tuple.Create("", 993), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/css/style.min.css")
, 993), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("/>\r\n");

            
            #line 21 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (File.Exists(Server.MapPath("~/areas/manager/content/css/style.css"))) {

            
            #line default
            #line hidden
WriteLiteral("    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1172), Tuple.Create("\"", 1216)
, Tuple.Create(Tuple.Create("", 1179), Tuple.Create<System.Object, System.Int32>(Href("~/areas/manager/content/css/style.css")
, 1179), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral("/>\r\n");

            
            #line 23 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1301), Tuple.Create("\"", 1366)
, Tuple.Create(Tuple.Create("", 1307), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/ext/jquery-1.7.2.min.js")
, 1307), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1413), Tuple.Create("\"", 1472)
, Tuple.Create(Tuple.Create("", 1419), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.manager.js")
, 1419), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1519), Tuple.Create("\"", 1585)
, Tuple.Create(Tuple.Create("", 1525), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/ext/chosen.jquery.min.js")
, 1525), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var siteroot = \"");

            
            #line 29 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                   Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var apikey = \"");

            
            #line 30 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                 Write(Html.APIKey("FE868D4F-797C-4E60-B876-64E6FC2424AA"));

            
            #line default
            #line hidden
WriteLiteral(@""";
        siteroot += !siteroot.endsWith(""/"") ? ""/"" : """";

        $(document).ready(function () {
            $("".message"").click(function () { $(this).fadeOut(""medium""); });

            $("".chzn-select"").chosen().trigger(""liszt:updated"");
        });
    </script>
");

            
            #line 39 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 39 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (!String.IsNullOrEmpty(ViewBag.Message)) {

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        setTimeout(function () {\r\n            $(\".sys-message\").slideUp();\r\n  " +
"      }, 2000);\r\n    </script>\r\n");

            
            #line 45 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 46 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container_12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid_12 header\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"home\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2423), Tuple.Create("\"", 2458)
            
            #line 52 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2430), Tuple.Create<System.Object, System.Int32>(Url.Action("index", "page")
            
            #line default
            #line hidden
, 2430), false)
);

WriteLiteral(">\r\n");

            
            #line 53 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                     if (File.Exists(Server.MapPath("~/areas/manager/content/img/logo.png")))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2608), Tuple.Create("\"", 2650)
, Tuple.Create(Tuple.Create("", 2614), Tuple.Create<System.Object, System.Int32>(Href("~/areas/manager/content/img/logo.png")
, 2614), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 2651), Tuple.Create("\"", 2707)
            
            #line 55 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2657), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.CurrentSite.MetaTitle
            
            #line default
            #line hidden
, 2657), false)
);

WriteLiteral(" />\r\n");

            
            #line 56 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2813), Tuple.Create("\"", 2864)
, Tuple.Create(Tuple.Create("", 2819), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/img/logo.png")
, 2819), false)
);

WriteLiteral(" alt=\"Piranha CMS\"");

WriteLiteral(" />\r\n");

            
            #line 60 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                    }
            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <div");

WriteLiteral(" class=\"site-title\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 62 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                     Write(Piranha.WebPages.WebPiranha.CurrentSite.MetaTitle);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <a");

WriteLiteral(" class=\"public-site\"");

WriteLiteral(" target=\"preview\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3101), Tuple.Create("\"", 3149)
            
            #line 63 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3108), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.GetSiteUrl()
            
            #line default
            #line hidden
, 3108), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 64 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                   Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n");

WriteLiteral("                ");

            
            #line 66 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("Partial/Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container_12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral("><h1>");

            
            #line 72 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1></div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container_12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"grid_12 toolbar-container\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 78 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(RenderSection("Toolbar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 80 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 80 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
             if (!String.IsNullOrEmpty(ViewBag.Message)) {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"grid_12 sys-message\"");

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 3806), Tuple.Create("\"", 3893)
, Tuple.Create(Tuple.Create("", 3814), Tuple.Create("box", 3814), true)
            
            #line 82 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3817), Tuple.Create<System.Object, System.Int32>(!String.IsNullOrEmpty(ViewBag.MessageCss) ? " " + ViewBag.MessageCss : ""
            
            #line default
            #line hidden
, 3817), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ico\"");

WriteLiteral("></div><p>");

            
            #line 84 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                             Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 88 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"content left\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 90 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"boxSysMsg\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2");

WriteLiteral(" id=\"SysMsgTitle\"");

WriteLiteral("></h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" id=\"SysMsgBody\"");

WriteLiteral("></p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"boxDialog\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral(" style=\"background-color: transparent\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" style=\"min-width: 510px;min-height:260px;\"");

WriteLiteral(">\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 108 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("Foot", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
